-- Users Table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    "profilePicture" TEXT,
    language TEXT NOT NULL,
    region TEXT NOT NULL,
    "gamesPlayed" JSON NOT NULL,
    "currentGame" TEXT NOT NULL,
    "currentGameId" TEXT NOT NULL,
    "lastActive" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isAdmin" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Group Chats Table
CREATE TABLE group_chats (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    "createdBy" INTEGER NOT NULL REFERENCES users(id),
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "adminIds" JSON NOT NULL DEFAULT '[]'
);

-- Group Members Table
CREATE TABLE group_members (
    id SERIAL PRIMARY KEY,
    "groupId" INTEGER NOT NULL REFERENCES group_chats(id),
    "userId" INTEGER NOT NULL REFERENCES users(id),
    "joinedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("groupId", "userId") -- Added unique constraint
);

-- Messages Table
CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    "fromUserId" INTEGER NOT NULL REFERENCES users(id),
    "toUserId" INTEGER REFERENCES users(id),
    "groupId" INTEGER REFERENCES group_chats(id),
    content TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isRead" BOOLEAN NOT NULL DEFAULT FALSE,
    "readAt" TIMESTAMP,
    type TEXT NOT NULL DEFAULT 'text',
    CONSTRAINT check_recipient CHECK (("toUserId" IS NOT NULL AND "groupId" IS NULL) OR ("toUserId" IS NULL AND "groupId" IS NOT NULL)) -- Added check constraint
);

-- Games Table
CREATE TABLE games (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    categories JSON NOT NULL,
    platforms JSON NOT NULL,
    contact TEXT,
    downloads INTEGER
);

-- Ideas Table
CREATE TABLE ideas (
    id SERIAL PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    votes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Idea Votes Table
CREATE TABLE idea_votes (
    id SERIAL PRIMARY KEY,
    idea_id INTEGER NOT NULL REFERENCES ideas(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (idea_id, user_id) -- Added unique constraint
);

-- Insert data into games table
INSERT INTO games (name, categories, platforms, contact, downloads) VALUES
('Elden Ring', '["Action", "RPG"]', '["PC", "Console"]', 'support@bandainamcoent.com', 20000000),
('God of War Ragnarök', '["Action", "Adventure"]', '["Console"]', 'support@playstation.com', 15000000),
('Genshin Impact', '["Action", "RPG"]', '["Mobile", "PC", "Console"]', 'genshin_cs@mihoyo.com', 100000000),
('Call of Duty: Warzone', '["Shooter", "Action"]', '["PC", "Console"]', 'support@activision.com', 125000000),
('Cyberpunk 2077', '["Action", "RPG"]', '["PC", "Console"]', 'help@cdprojektred.com', 18000000),
('Animal Crossing: New Horizons', '["Simulation"]', '["Console"]', 'support@nintendo.com', 40000000),
('Among Us', '["Strategy", "Survival"]', '["Mobile", "PC", "Console"]', 'support@innersloth.com', 500000000),
('Valorant', '["Shooter", "Strategy"]', '["PC"]', 'support@riotgames.com', 22000000),
('Roblox', '["Adventure", "Simulation"]', '["PC", "Mobile", "Console"]', 'info@roblox.com', 380000000),
('Fortnite', '["Shooter", "Survival"]', '["PC", "Console", "Mobile"]', 'help@epicgames.com', 350000000),
('Minecraft', '["Survival", "Adventure"]', '["PC", "Console", "Mobile"]', 'support@mojang.com', 238000000),
('The Last of Us Part II', '["Action", "Adventure"]', '["Console"]', 'support@naughtydog.com', 10000000),
('Hades', '["Action", "RPG"]', '["PC", "Console"]', 'support@supergiantgames.com', 7000000),
('Fall Guys', '["Platformer"]', '["PC", "Console"]', 'support@mediatonic.co.uk', 50000000),
('Resident Evil Village', '["Action", "Survival"]', '["PC", "Console"]', 'support@capcom.com', 6000000),
('Pokémon Legends: Arceus', '["RPG", "Adventure"]', '["Console"]', 'support@pokemon.com', 13500000),
('FIFA 23', '["Sports"]', '["PC", "Console"]', 'help@ea.com', 35000000),
('Horizon Forbidden West', '["Action", "RPG"]', '["Console"]', 'support@guerrilla-games.com', 8200000),
('Ghost of Tsushima', '["Action", "Adventure"]', '["Console"]', 'support@suckerpunch.com', 9500000),
('Marvel''s Spider-Man: Miles Morales', '["Action", "Adventure"]', '["PC", "Console"]', 'support@insomniacgames.com', 6800000),
('Stardew Valley', '["Simulation", "RPG"]', '["PC", "Console", "Mobile"]', 'contact@stardewvalley.net', 20000000),
('Microsoft Flight Simulator', '["Simulation"]', '["PC", "Console"]', 'flightsim-support@microsoft.com', 2000000),
('Demon''s Souls (Remake)', '["Action", "RPG"]', '["Console"]', 'support@bluepointgames.com', 1500000),
('It Takes Two', '["Adventure", "Platformer"]', '["PC", "Console"]', 'support@hazelight.se', 10000000),
('Deathloop', '["Action", "Shooter"]', '["PC", "Console"]', 'support@arkane-studios.com', 3000000),
('Returnal', '["Action", "Shooter"]', '["PC", "Console"]', 'support@housemarque.com', 2000000),
('Monster Hunter Rise', '["Action", "RPG"]', '["PC", "Console"]', 'support@capcom.com', 11000000),
('Final Fantasy VII Remake', '["RPG", "Action"]', '["PC", "Console"]', 'support@square-enix.com', 7000000),
('Assassin''s Creed Valhalla', '["Action", "Adventure"]', '["PC", "Console"]', 'support@ubisoft.com', 20000000),
('Pokémon Brilliant Diamond and Shining Pearl', '["RPG"]', '["Console"]', 'support@pokemon.com', 14000000),
('Guardians of the Galaxy', '["Action", "Adventure"]', '["PC", "Console"]', 'support@eidosmontreal.com', 3000000),
('Ratchet & Clank: Rift Apart', '["Action", "Platformer"]', '["Console"]', 'support@insomniacgames.com', 1500000),
('Kena: Bridge of Spirits', '["Action", "Adventure"]', '["PC", "Console"]', 'support@emberlab.com', 2000000),
('Metroid Dread', '["Action", "Adventure"]', '["Console"]', 'support@nintendo.com', 3000000),
('New World', '["RPG", "Adventure"]', '["PC"]', 'support@amazonagames.com', 25000000),
('Lost Ark', '["RPG", "Action"]', '["PC"]', 'support@playlostark.com', 20000000),
('Psychonauts 2', '["Platformer", "Adventure"]', '["PC", "Console"]', 'support@doublefine.com', 2000000),
('Age of Empires IV', '["Strategy"]', '["PC"]', 'support@ageofempires.com', 3000000),
('Back 4 Blood', '["Shooter", "Action"]', '["PC", "Console"]', 'support@turtlerockstudios.com', 6000000),
('Far Cry 6', '["Action", "Shooter"]', '["PC", "Console"]', 'support@ubisoft.com', 10000000),
('Dying Light 2', '["Action", "Survival"]', '["PC", "Console"]', 'support@techland.pl', 5000000),
('Battlefield 2042', '["Shooter", "Action"]', '["PC", "Console"]', 'help@ea.com', 4500000),
('Gran Turismo 7', '["Racing", "Simulation"]', '["Console"]', 'support@polyphony.co.jp', 8000000),
('Pokémon Scarlet and Violet', '["RPG", "Adventure"]', '["Console"]', 'support@pokemon.com', 20000000),
('Splatoon 3', '["Shooter", "Action"]', '["Console"]', 'support@nintendo.com', 10000000),
('Tiny Tina''s Wonderlands', '["Shooter", "RPG"]', '["PC", "Console"]', 'support@gearboxsoftware.com', 5000000),
('Triangle Strategy', '["Strategy", "RPG"]', '["Console"]', 'support@square-enix.com', 1000000),
('Kirby and the Forgotten Land', '["Platformer", "Adventure"]', '["Console"]', 'support@nintendo.com', 5000000),
('Tunic', '["Action", "Adventure"]', '["PC", "Console"]', 'support@finji.co', 1000000),
('SIFU', '["Action", "Fighting"]', '["PC", "Console"]', 'support@sloclap.com', 2000000),
('Ghostwire: Tokyo', '["Action", "Adventure"]', '["PC", "Console"]', 'support@tangogameworks.com', 1500000),
('Horizon Zero Dawn', '["Action", "RPG"]', '["PC", "Console"]', 'support@guerrilla-games.com', 20000000),
('Chorus', '["Action", "Adventure"]', '["PC", "Console"]', 'support@fishingcactus.com', 1000000),
('Rainbow Six Extraction', '["Shooter", "Strategy"]', '["PC", "Console"]', 'support@ubisoft.com', 3000000),
('Pokemon Legends: Arceus', '["RPG", "Adventure"]', '["Console"]', 'support@pokemon.com', 14500000),
('Forza Horizon 5', '["Racing", "Simulation"]', '["PC", "Console"]', 'support@playground-games.com', 25000000),
('Halo Infinite', '["Shooter", "Action"]', '["PC", "Console"]', 'support@343industries.com', 20000000),
('The Ascent', '["Action", "RPG"]', '["PC", "Console"]', 'support@curve-digital.com', 1000000),
('Death''s Door', '["Action", "Adventure"]', '["PC", "Console"]', 'support@devolverdigital.com', 1500000),
('Little Nightmares II', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@bandainamco.com', 2000000),
('Hitman 3', '["Action", "Stealth"]', '["PC", "Console"]', 'support@ioi.dk', 5000000),
('Resident Evil 4 Remake', '["Action", "Survival"]', '["PC", "Console"]', 'support@capcom.com', 5000000),
('The Callisto Protocol', '["Survival", "Action"]', '["PC", "Console"]', 'support@strikingdistancestudios.com', 2000000),
('High On Life', '["Shooter", "Comedy"]', '["PC", "Console"]', 'support@squanchtendo.com', 3000000),
('Marvel''s Midnight Suns', '["Strategy", "RPG"]', '["PC", "Console"]', 'support@firaxis.com', 2000000),
('God of War (PC Port)', '["Action", "Adventure"]', '["PC"]', 'support@santamonicastudio.com', 5000000),
('Sniper Elite 5', '["Shooter", "Stealth"]', '["PC", "Console"]', 'support@rebellion.co.uk', 2000000),
('Evil Dead: The Game', '["Action", "Survival"]', '["PC", "Console"]', 'support@saber.games', 1500000),
('Cult of the Lamb', '["Simulation", "Action"]', '["PC", "Console"]', 'support@devolverdigital.com', 2000000),
('Xenoblade Chronicles 3', '["RPG", "Adventure"]', '["Console"]', 'support@monolithsoft.co.jp', 2000000),
('MultiVersus', '["Fighting", "Action"]', '["PC", "Console"]', 'support@wbgames.com', 20000000),
('Saints Row Reboot', '["Action", "Adventure"]', '["PC", "Console"]', 'support@deepsilver.com', 2000000),
('Soul Hackers 2', '["RPG", "Strategy"]', '["PC", "Console"]', 'support@atlus.com', 1000000),
('The Last of Us Part I', '["Action", "Adventure"]', '["PC", "Console"]', 'support@naughtydog.com', 6000000),
('The DioField Chronicle', '["Strategy", "RPG"]', '["PC", "Console"]', 'support@square-enix.com', 500000),
('Overwatch 2', '["Shooter", "Action"]', '["PC", "Console"]', 'support@blizzard.com', 25000000),
('Mario + Rabbids Sparks of Hope', '["Strategy", "Adventure"]', '["Console"]', 'support@ubisoft.com', 3000000),
('Gotham Knights', '["Action", "Adventure"]', '["PC", "Console"]', 'support@wbgames.com', 2000000),
('Call of Duty: Modern Warfare II', '["Shooter", "Action"]', '["PC", "Console"]', 'support@activision.com', 30000000),
('Bayonetta 3', '["Action", "Adventure"]', '["Console"]', 'support@platinumgames.com', 1000000),
('Star Wars Jedi: Survivor', '["Action", "Adventure"]', '["PC", "Console"]', 'help@ea.com', 10000000),
('The Legend of Zelda: Tears of the Kingdom', '["Action", "Adventure"]', '["Console"]', 'support@nintendo.com', 20000000),
('Diablo IV', '["Action", "RPG"]', '["PC", "Console"]', 'support@blizzard.com', 12000000),
('Street Fighter 6', '["Fighting"]', '["PC", "Console"]', 'support@capcom.com', 3000000),
('Hogwarts Legacy', '["RPG", "Adventure"]', '["PC", "Console"]', 'support@wbgames.com', 15000000),
('Atomic Heart', '["Action", "RPG"]', '["PC", "Console"]', 'support@mundfish.com', 2000000),
('Dead Space Remake', '["Survival", "Action"]', '["PC", "Console"]', 'help@ea.com', 3000000),
('Hi-Fi Rush', '["Action", "Rhythm"]', '["PC", "Console"]', 'support@tangogameworks.com', 2500000),
('Wo Long: Fallen Dynasty', '["Action", "RPG"]', '["PC", "Console"]', 'support@koeitecmo.com', 1000000),
('Resident Evil 4 (Remake)', '["Action", "Survival"]', '["PC", "Console"]', 'support@capcom.com', 5000000),
('Dead Island 2', '["Action", "Survival"]', '["PC", "Console"]', 'support@deepsilver.com', 3000000),
-- Duplicate Star Wars Jedi: Survivor removed
-- Duplicate The Legend of Zelda: Tears of the Kingdom removed
-- Duplicate Diablo IV removed
('Final Fantasy XVI', '["RPG", "Action"]', '["Console"]', 'support@square-enix.com', 5000000),
('Baldur''s Gate 3', '["RPG", "Strategy"]', '["PC", "Console"]', 'support@larian.com', 10000000),
('Starfield', '["RPG", "Adventure"]', '["PC", "Console"]', 'help@bethesda.net', 12000000),
('Armored Core VI: Fires of Rubicon', '["Action"]', '["PC", "Console"]', 'support@fromsoftware.jp', 3000000),
('Spider-Man 2', '["Action", "Adventure"]', '["Console"]', 'support@insomniacgames.com', 8000000),
('Alan Wake 2', '["Action", "Adventure"]', '["PC", "Console"]', 'support@remedygames.com', 2000000),
('Super Mario Bros. Wonder', '["Platformer"]', '["Console"]', 'support@nintendo.com', 10000000),
('Lords of the Fallen', '["Action", "RPG"]', '["PC", "Console"]', 'support@ci-games.com', 1000000),
('Dead Rising Deluxe Remaster', '["Action", "Survival"]', '["PC", "Console"]', 'support@capcom.com', 500000),
('Mortal Kombat 1', '["Fighting"]', '["PC", "Console"]', 'support@wbgames.com', 5000000),
('Lies of P', '["Action", "RPG"]', '["PC", "Console"]', 'support@neowiz.com', 2000000),
('The Crew Motorfest', '["Racing"]', '["PC", "Console"]', 'support@ubisoft.com', 2000000),
('Forza Motorsport', '["Racing", "Simulation"]', '["PC", "Console"]', 'support@turn10studios.com', 8000000),
('Cyberpunk 2077: Phantom Liberty', '["RPG", "Action"]', '["PC", "Console"]', 'help@cdprojektred.com', 5000000),
('Assassin''s Creed Mirage', '["Action", "Adventure"]', '["PC", "Console"]', 'support@ubisoft.com', 7000000),
('Call of Duty: Modern Warfare III', '["Shooter", "Action"]', '["PC", "Console"]', 'support@activision.com', 25000000),
('Super Mario RPG Remake', '["RPG"]', '["Console"]', 'support@nintendo.com', 3000000),
('Dragon''s Dogma 2', '["RPG", "Action"]', '["PC", "Console"]', 'support@capcom.com', 3000000),
('Star Wars Outlaws', '["Action", "Adventure"]', '["PC", "Console"]', 'support@ubisoft.com', 4000000),
('Tekken 8', '["Fighting"]', '["PC", "Console"]', 'support@bandainamcoent.com', 2000000),
('Like a Dragon: Infinite Wealth', '["RPG", "Action"]', '["PC", "Console"]', 'support@sega.com', 1000000),
('Monster Hunter Wilds', '["Action", "RPG"]', '["PC", "Console"]', 'support@capcom.com', 7000000),
('Final Fantasy VII Rebirth', '["RPG", "Action"]', '["Console"]', 'support@square-enix.com', 5000000),
('Harry Potter: Quidditch Champions', '["Sports", "Action"]', '["PC", "Console"]', 'support@wbgames.com', 3000000),
('Mobile Legends: Bang Bang', '["Action", "Strategy"]', '["Mobile"]', 'mobilelegends@moonton.com', 1000000000),
('PUBG Mobile', '["Shooter", "Survival"]', '["Mobile"]', 'support@pubgmobile.com', 1000000000),
('Call of Duty: Mobile', '["Shooter", "Action"]', '["Mobile"]', 'support@activision.com', 500000000),
('Free Fire', '["Shooter", "Survival"]', '["Mobile"]', 'support@garena.com', 1500000000),
('Subway Surfers', '["Action", "Platformer"]', '["Mobile"]', 'support@kiloo.com', 3000000000),
('Candy Crush Saga', '["Puzzle"]', '["Mobile"]', 'support@king.com', 2500000000),
('Pokémon GO', '["Adventure", "RPG"]', '["Mobile"]', 'support@nianticlabs.com', 1000000000),
('Homescapes', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@playrix.com', 350000000),
('Clash of Clans', '["Strategy", "Simulation"]', '["Mobile"]', 'support@supercell.com', 500000000),
('Clash Royale', '["Strategy", "Action"]', '["Mobile"]', 'support@supercell.com', 500000000),
('Brawl Stars', '["Action", "Strategy"]', '["Mobile"]', 'support@supercell.com', 300000000),
('Coin Master', '["Simulation", "Puzzle"]', '["Mobile"]', 'support@moonactive.com', 100000000),
('8 Ball Pool', '["Sports", "Simulation"]', '["Mobile"]', 'support@miniclip.com', 500000000),
('RAID: Shadow Legends', '["RPG", "Strategy"]', '["Mobile"]', 'support@plarium.com', 50000000),
('Rise of Kingdoms', '["Strategy", "Simulation"]', '["Mobile"]', 'support@lilithgames.com', 100000000),
('State of Survival', '["Strategy", "Survival"]', '["Mobile"]', 'support@kinggroup.com', 100000000),
('Lords Mobile', '["Strategy", "RPG"]', '["Mobile"]', 'support@igg.com', 200000000),
('Gardenscapes', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@playrix.com', 250000000),
('Toon Blast', '["Puzzle"]', '["Mobile"]', 'support@peakgames.com', 80000000),
('Candy Crush Soda Saga', '["Puzzle"]', '["Mobile"]', 'support@king.com', 500000000),
('Empires & Puzzles', '["Puzzle", "RPG"]', '["Mobile"]', 'support@smallgiantgames.com', 50000000),
('Royal Match', '["Puzzle"]', '["Mobile"]', 'support@dreamgames.com', 100000000),
('Evony: The King''s Return', '["Strategy", "Simulation"]', '["Mobile"]', 'support@evony.com', 50000000),
('Township', '["Simulation", "Strategy"]', '["Mobile"]', 'support@playrix.com', 100000000),
('Fishdom', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@playrix.com', 100000000),
('Merge Dragons!', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@gramgames.com', 50000000),
('Project Makeover', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@magictaggames.com', 50000000),
('Honor of Kings', '["Action", "Strategy"]', '["Mobile"]', 'support@tencent.com', 300000000),
('Summoners War', '["RPG", "Strategy"]', '["Mobile"]', 'support@com2us.com', 100000000),
('AFK Arena', '["RPG", "Strategy"]', '["Mobile"]', 'support@lilithgames.com', 50000000),
('Game of Thrones: Conquest', '["Strategy", "Simulation"]', '["Mobile"]', 'support@wbgames.com', 10000000),
('Idle Heroes', '["RPG", "Strategy"]', '["Mobile"]', 'support@droidhang.com', 50000000),
('Match Masters', '["Puzzle"]', '["Mobile"]', 'support@funtomic.com', 10000000),
('June''s Journey', '["Puzzle", "Adventure"]', '["Mobile"]', 'support@wooga.com', 10000000),
('Pocket Worlds 3D', '["Simulation", "Adventure"]', '["Mobile"]', 'support@pocketworlds.com', 10000000),
('Marvel Strike Force', '["RPG", "Strategy"]', '["Mobile"]', 'support@scopely.com', 30000000),
('Star Wars: Galaxy of Heroes', '["RPG", "Strategy"]', '["Mobile"]', 'help@ea.com', 50000000),
('Harry Potter: Magic Awakened', '["RPG", "Strategy"]', '["Mobile"]', 'support@netease.com', 20000000),
('Disney Mirrorverse', '["RPG", "Action"]', '["Mobile"]', 'support@kabam.com', 10000000),
('Merge Mansion', '["Puzzle", "Simulation"]', '["Mobile"]', 'support@metacore.com', 20000000),
('Marvel Contest of Champions', '["Fighting", "Action"]', '["Mobile"]', 'support@kabam.com', 100000000),
('FIFA Mobile', '["Sports", "Simulation"]', '["Mobile"]', 'help@ea.com', 100000000),
('Apex Legends Mobile', '["Shooter", "Action"]', '["Mobile"]', 'help@ea.com', 50000000),
('League of Legends: Wild Rift', '["Action", "Strategy"]', '["Mobile"]', 'support@riotgames.com', 50000000),
('Diablo Immortal', '["Action", "RPG"]', '["Mobile"]', 'support@blizzard.com', 30000000),
('Clash Mini', '["Strategy"]', '["Mobile"]', 'support@supercell.com', 10000000),
('Everdale', '["Simulation", "Strategy"]', '["Mobile"]', 'support@supercell.com', 10000000),
('Angry Birds Journey', '["Puzzle", "Action"]', '["Mobile"]', 'support@rovio.com', 30000000),
('Words With Friends 2', '["Puzzle"]', '["Mobile"]', 'support@zynga.com', 100000000),
('Family Island', '["Simulation", "Adventure"]', '["Mobile"]', 'support@melsoft.com', 25000000),
('Big Farm Mobile Harvest', '["Simulation", "Strategy"]', '["Mobile"]', 'support@goodgamestudios.com', 10000000),
('Shadow Fight Arena', '["Fighting", "Action"]', '["Mobile"]', 'support@nekki.com', 20000000),
('Magic: The Gathering Arena', '["Strategy", "Card Game"]', '["PC", "Mobile"]', 'support@wizards.com', 10000000),
('Hearthstone', '["Strategy", "Card Game"]', '["PC", "Mobile"]', 'support@blizzard.com', 100000000),
('Sky: Children of the Light', '["Adventure", "Simulation"]', '["Mobile"]', 'support@thatgamecompany.com', 50000000),
('Monument Valley 2', '["Puzzle", "Adventure"]', '["Mobile"]', 'support@ustwo.com', 10000000),
('Asphalt 9: Legends', '["Racing"]', '["Mobile"]', 'support@gameloft.com', 100000000),
('Mario Kart Tour', '["Racing"]', '["Mobile"]', 'support@nintendo.com', 200000000),
('Honkai: Star Rail', '["RPG", "Strategy"]', '["Mobile", "PC"]', 'genshin_cs@mihoyo.com', 30000000),
('Zenless Zone Zero', '["Action", "RPG"]', '["Mobile", "PC"]', 'support@mihoyo.com', 10000000),
('Wuthering Waves', '["Action", "RPG"]', '["Mobile", "PC"]', 'support@kurogame.com', 10000000),
('Punishing: Gray Raven', '["Action", "RPG"]', '["Mobile"]', 'support@kurogame.com', 10000000),
('Arknights', '["Strategy", "RPG"]', '["Mobile"]', 'support@hypergryph.com', 20000000),
('Blue Archive', '["RPG", "Strategy"]', '["Mobile"]', 'support@nexon.com', 10000000),
('Another Eden', '["RPG", "Adventure"]', '["Mobile"]', 'support@wfs.games', 10000000),
('Girls'' Frontline', '["Strategy", "RPG"]', '["Mobile"]', 'support@sunborngame.com', 10000000),
('Azur Lane', '["Shooter", "RPG"]', '["Mobile"]', 'support@yostar.com', 15000000),
('Cookie Run: Kingdom', '["RPG", "Strategy"]', '["Mobile"]', 'support@devsisters.com', 50000000),
('Guardian Tales', '["RPG", "Adventure"]', '["Mobile"]', 'support@kakaogames.com', 20000000),
('Fate/Grand Order', '["RPG", "Strategy"]', '["Mobile"]', 'support@aniplex.co.jp', 50000000),
('Goddess of Victory: Nikke', '["Shooter", "RPG"]', '["Mobile"]', 'support@shift-up.co.kr', 15000000),
('Tower of Fantasy', '["RPG", "Adventure"]', '["Mobile", "PC"]', 'support@levelinfinite.com', 20000000),
('Ni no Kuni: Cross Worlds', '["RPG", "Adventure"]', '["Mobile"]', 'support@netmarble.com', 10000000),
('Seven Knights 2', '["RPG", "Strategy"]', '["Mobile"]', 'support@netmarble.com', 10000000),
('Disney Twisted-Wonderland', '["RPG", "Simulation"]', '["Mobile"]', 'support@aniplex.co.jp', 8000000),
('Honkai Impact 3rd', '["Action", "RPG"]', '["Mobile", "PC"]', 'support@mihoyo.com', 30000000),
('Tears of Themis', '["RPG", "Simulation"]', '["Mobile"]', 'support@mihoyo.com', 10000000),
('Counter: Side', '["RPG", "Strategy"]', '["Mobile"]', 'support@studiobside.com', 10000000),
('Identity V', '["Survival", "Strategy"]', '["Mobile"]', 'support@netease.com', 50000000),
('Teamfight Tactics', '["Strategy"]', '["Mobile", "PC"]', 'support@riotgames.com', 50000000),
('Pokémon Unite', '["Strategy", "Action"]', '["Mobile", "Console"]', 'support@pokemon.com', 50000000),
('Black Desert Mobile', '["RPG", "Adventure"]', '["Mobile"]', 'support@pearlabyss.com', 30000000),
('Path of Exile Mobile', '["Action", "RPG"]', '["Mobile"]', 'support@grindinggear.com', 15000000),
('Echoes of Mana', '["RPG", "Action"]', '["Mobile"]', 'support@square-enix.com', 5000000),
('Idle Miner Tycoon', '["Simulation", "Strategy"]', '["Mobile"]', 'support@fluffyfairygames.com', 100000000),
('Dragon City Mobile', '["Simulation", "Strategy"]', '["Mobile"]', 'support@socialpoint.es', 100000000),
('Warpath', '["Strategy", "Simulation"]', '["Mobile"]', 'support@lilithgames.com', 10000000),
('Top War: Battle Game', '["Strategy", "Simulation"]', '["Mobile"]', 'support@topwargame.com', 50000000),
('Gun War: Shooting Games', '["Shooter", "Action"]', '["Mobile"]', 'support@shooter.com', 50000000),
('Hill Climb Racing 2', '["Racing"]', '["Mobile"]', 'support@fingersoft.com', 100000000),
('World of Tanks Blitz', '["Action", "Simulation"]', '["Mobile"]', 'support@wargaming.net', 150000000),
('Plants vs. Zombies 2', '["Strategy"]', '["Mobile"]', 'help@ea.com', 200000000),
('My Talking Tom 2', '["Simulation"]', '["Mobile"]', 'support@outfit7.com', 300000000),
('Stumble Guys', '["Action", "Platformer"]', '["Mobile"]', 'support@stumbleguys.com', 100000000),
('CSR Racing 2', '["Racing", "Simulation"]', '["Mobile"]', 'support@naturalmotion.com', 130000000),
('Lineage 2: Revolution', '["RPG", "Adventure"]', '["Mobile"]', 'support@netmarble.com', 30000000),
('Crossy Road', '["Action", "Arcade"]', '["Mobile"]', 'support@hipsterwhale.com', 200000000),
('Temple Run 2', '["Action", "Platformer"]', '["Mobile"]', 'support@imangi.com', 500000000),
('King of Avalon', '["Strategy", "Simulation"]', '["Mobile"]', 'support@funplus.com', 100000000),
('Guns of Glory', '["Strategy", "Simulation"]', '["Mobile"]', 'support@funplus.com', 50000000),
('Cooking Fever', '["Simulation"]', '["Mobile"]', 'support@nordcurrent.com', 200000000),
('Traffic Rider', '["Racing"]', '["Mobile"]', 'support@soner.com', 100000000),
('Golf Clash', '["Sports", "Simulation"]', '["Mobile"]', 'support@playdemic.com', 50000000),
('Art of Conquest', '["Strategy", "RPG"]', '["Mobile"]', 'support@lilithgames.com', 10000000),
('Clash Quest', '["Puzzle", "Strategy"]', '["Mobile"]', 'support@supercell.com', 5000000),
('Last Day on Earth: Survival', '["Survival", "Action"]', '["Mobile"]', 'support@kefirgames.com', 100000000),
('Garena Free Fire MAX', '["Shooter", "Survival"]', '["Mobile"]', 'support@garena.com', 200000000),
('Hay Day', '["Simulation", "Strategy"]', '["Mobile"]', 'support@supercell.com', 100000000),
('BitLife', '["Simulation"]', '["Mobile"]', 'support@candywriter.com', 100000000),
('Design Home', '["Simulation", "Puzzle"]', '["Mobile"]', 'support@crowdstar.com', 80000000),
('Homicide Squad', '["Puzzle", "Adventure"]', '["Mobile"]', 'support@g5e.com', 10000000),
('Manor Matters', '["Puzzle", "Adventure"]', '["Mobile"]', 'support@playrix.com', 50000000),
('Apex Craft', '["Adventure", "Simulation"]', '["Mobile"]', 'support@crafting.io', 10000000),
('Avakin Life', '["Simulation", "Adventure"]', '["Mobile"]', 'support@lockwood.com', 100000000),
('Harry Potter: Hogwarts Mystery', '["Adventure", "RPG"]', '["Mobile"]', 'support@jamcity.com', 80000000),
('GRID Autosport', '["Racing", "Simulation"]', '["PC", "Console", "Mobile"]', 'support@feralinteractive.com', 10000000),
('MARVEL Future Fight', '["Action", "RPG"]', '["Mobile"]', 'support@netmarble.com', 120000000),
('Disney Emoji Blitz', '["Puzzle"]', '["Mobile"]', 'support@jamcity.com', 50000000),
('Cookie Run: OvenBreak', '["Platformer", "Action"]', '["Mobile"]', 'support@devsisters.com', 50000000),
('Toca Life World', '["Simulation", "Education"]', '["Mobile"]', 'support@tocaboca.com', 50000000),
('Monopoly GO!', '["Simulation", "Strategy"]', '["Mobile"]', 'support@scopely.com', 100000000),
('Angry Birds 2', '["Puzzle", "Action"]', '["Mobile"]', 'support@rovio.com', 100000000),
('Fallout Shelter', '["Simulation", "Strategy"]', '["Mobile"]', 'help@bethesda.net', 120000000),
('Slay the Spire', '["Strategy", "Card Game"]', '["PC", "Console", "Mobile"]', 'support@megacrit.com', 5000000),
('Dead Cells', '["Action", "Platformer"]', '["PC", "Console", "Mobile"]', 'support@motiontwin.com', 8000000),
('Terraria', '["Adventure", "Survival"]', '["PC", "Console", "Mobile"]', 'support@re-logic.com', 35000000),
('Teamfight Manager', '["Simulation", "Strategy"]', '["PC"]', 'support@teamfightmanager.com', 500000),
('Vampire Survivors', '["Action", "Survival"]', '["PC", "Console", "Mobile"]', 'support@poncle.games', 10000000),
('Valheim', '["Survival", "Adventure"]', '["PC"]', 'support@irongatestudio.se', 10000000),
('Disco Elysium', '["RPG", "Adventure"]', '["PC", "Console"]', 'support@zaum.ee', 3000000),
('Outer Wilds', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@mobiusdigitalgames.com', 2000000),
('Hollow Knight: Silksong', '["Platformer", "Adventure"]', '["PC", "Console"]', 'support@teamcherry.com.au', 4000000),
('Undertale', '["RPG", "Adventure"]', '["PC", "Console"]', 'support@tobyfox.net', 10000000),
('Inscryption', '["Card Game", "Puzzle"]', '["PC", "Console"]', 'support@devolvedigital.com', 2000000),
('V Rising', '["Survival", "Action"]', '["PC"]', 'support@stunlock.com', 3000000),
('Dave the Diver', '["Adventure", "Simulation"]', '["PC", "Console"]', 'support@mintrocketgames.com', 5000000),
('Darkest Dungeon II', '["RPG", "Strategy"]', '["PC", "Console"]', 'support@redhookgames.com', 1000000),
('Satisfactory', '["Simulation", "Strategy"]', '["PC"]', 'support@coffeestainstudios.com', 4000000),
('Planet Zoo', '["Simulation", "Strategy"]', '["PC"]', 'support@frontier.co.uk', 3000000),
('Factorio', '["Simulation", "Strategy"]', '["PC"]', 'support@factorio.com', 3500000),
('Half-Life 2', '["Shooter", "Adventure"]', '["PC", "Console"]', 'support@valvesoftware.com', 25000000),
('Portal 2', '["Puzzle", "Adventure"]', '["PC", "Console"]', 'support@valvesoftware.com', 20000000),
('DOOM Eternal', '["Shooter", "Action"]', '["PC", "Console"]', 'support@bethesda.net', 15000000),
('Left 4 Dead 2', '["Shooter", "Co-op"]', '["PC", "Console"]', 'support@valvesoftware.com', 30000000),
('XCOM 2', '["Strategy", "Tactical"]', '["PC", "Console"]', 'support@firaxis.com', 8000000),
('Frostpunk', '["Simulation", "Strategy"]', '["PC", "Console"]', 'support@11bitstudios.com', 5000000),
('The Binding of Isaac: Rebirth', '["Roguelike", "Action"]', '["PC", "Console"]', 'support@nicholas.io', 6000000),
('Papers, Please', '["Puzzle", "Simulation"]', '["PC", "Mobile"]', 'support@dukope.com', 4000000),
('Baba Is You', '["Puzzle"]', '["PC", "Console"]', 'support@hempuli.com', 3000000),
('No Man''s Sky', '["Adventure", "Survival"]', '["PC", "Console", "Mobile"]', 'support@hellogames.co.uk', 12000000),
('Sea of Thieves', '["Action", "Adventure"]', '["PC", "Console"]', 'support@seaofthieves.com', 25000000),
('Phasmophobia', '["Horror", "Co-op"]', '["PC"]', 'support@kineticgames.co.uk', 7000000),
('Deep Rock Galactic', '["Shooter", "Co-op"]', '["PC", "Console"]', 'support@ghostship.dk', 6000000),
('Cities: Skylines', '["Simulation", "Strategy"]', '["PC", "Console"]', 'support@paradoxplaza.com', 12000000),
('Crusader Kings III', '["Strategy", "RPG"]', '["PC", "Console"]', 'support@paradoxplaza.com', 3000000),
('Subnautica', '["Adventure", "Survival"]', '["PC", "Console"]', 'support@unknownworlds.com', 8000000),
('Subnautica: Below Zero', '["Adventure", "Survival"]', '["PC", "Console"]', 'support@unknownworlds.com', 4000000),
('Total War: Warhammer III', '["Strategy"]', '["PC"]', 'support@creative-assembly.com', 2500000),
('RimWorld', '["Simulation", "Strategy"]', '["PC"]', 'support@ludeon.com', 4000000),
('Stray', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@annapurnainteractive.com', 8000000),
('A Plague Tale: Requiem', '["Action", "Adventure"]', '["PC", "Console"]', 'support@focus-home.com', 3000000),
('Control', '["Action", "Adventure"]', '["PC", "Console"]', 'support@remedygames.com', 4000000),
('Metro Exodus', '["Shooter", "Action"]', '["PC", "Console"]', 'support@4a-games.com.mt', 6000000),
('The Witcher 3: Wild Hunt', '["Action", "RPG"]', '["PC", "Console"]', 'help@cdprojektred.com', 40000000),
('Red Dead Redemption 2', '["Action", "Adventure"]', '["PC", "Console"]', 'support@rockstargames.com', 45000000),
('Grand Theft Auto V', '["Action", "Adventure"]', '["PC", "Console"]', 'support@rockstargames.com', 170000000),
('Borderlands 3', '["Shooter", "RPG"]', '["PC", "Console"]', 'support@gearboxsoftware.com', 15000000),
('Project Zomboid', '["Survival", "RPG"]', '["PC"]', 'support@theindiestone.com', 3000000),
('7 Days to Die', '["Survival", "Action"]', '["PC"]', 'support@thefunpimps.com', 4000000),
('Dwarf Fortress', '["Simulation", "Strategy"]', '["PC"]', 'support@bay12games.com', 1000000),
('Oxygen Not Included', '["Simulation", "Strategy"]', '["PC"]', 'support@klei.com', 3000000),
('Kingdom Come: Deliverance', '["Action", "RPG"]', '["PC", "Console"]', 'support@warhorsestudios.cz', 5000000),
('Mount & Blade II: Bannerlord', '["Action", "RPG", "Strategy"]', '["PC", "Console"]', 'support@taleworlds.com', 6000000),
('Sekiro: Shadows Die Twice', '["Action", "Adventure"]', '["PC", "Console"]', 'support@fromsoftware.jp', 10000000),
('Dark Souls III', '["Action", "RPG"]', '["PC", "Console"]', 'support@bandainamcoent.com', 15000000),
('The Forest', '["Survival", "Horror"]', '["PC"]', 'support@endnightgames.com', 10000000),
('Sons of the Forest', '["Survival", "Horror"]', '["PC"]', 'support@endnightgames.com', 4000000),
('Rust', '["Survival", "Action"]', '["PC"]', 'support@facepunchstudios.com', 12000000),
('Hearts of Iron IV', '["Strategy"]', '["PC"]', 'support@paradoxplaza.com', 4000000),
('Europa Universalis IV', '["Strategy"]', '["PC"]', 'support@paradoxplaza.com', 3000000),
('Stellaris', '["Strategy", "Sci-Fi"]', '["PC"]', 'support@paradoxplaza.com', 5000000),
('Monster Hunter: World', '["Action", "RPG"]', '["PC", "Console"]', 'support@capcom.com', 20000000),
('Divinity: Original Sin 2', '["RPG", "Strategy"]', '["PC", "Console"]', 'support@larian.com', 7000000),
('Pillars of Eternity II: Deadfire', '["RPG"]', '["PC", "Console"]', 'support@obsidian.net', 1000000),
('Warframe', '["Action", "Shooter"]', '["PC", "Console"]', 'support@digitalextremes.com', 50000000),
('Path of Exile', '["Action", "RPG"]', '["PC"]', 'support@grindinggear.com', 20000000),
('Outer Worlds', '["RPG", "Action"]', '["PC", "Console"]', 'support@obsidian.net', 5000000),
('GreedFall', '["Action", "RPG"]', '["PC", "Console"]', 'support@focus-home.com', 2000000),
('The Elder Scrolls V: Skyrim', '["RPG", "Adventure"]', '["PC", "Console"]', 'help@bethesda.net', 60000000),
('Fallout 4', '["RPG", "Action"]', '["PC", "Console"]', 'help@bethesda.net', 20000000),
('Watch Dogs: Legion', '["Action", "Adventure"]', '["PC", "Console"]', 'support@ubisoft.com', 5000000),
('Dying Light', '["Action", "Survival"]', '["PC", "Console"]', 'support@techland.pl', 8000000),
('Prey', '["Action", "Sci-Fi"]', '["PC", "Console"]', 'support@bethesda.net', 3000000),
('A Total War Saga: TROY', '["Strategy"]', '["PC"]', 'support@creative-assembly.com', 1500000),
('Total War: THREE KINGDOMS', '["Strategy"]', '["PC"]', 'support@creative-assembly.com', 3000000),
('Civilization VI', '["Strategy"]', '["PC", "Console", "Mobile"]', 'support@2k.com', 10000000),
('Persona 5 Royal', '["RPG", "Strategy"]', '["Console"]', 'support@atlus.com', 7000000),
('Yakuza: Like a Dragon', '["RPG", "Action"]', '["PC", "Console"]', 'support@sega.com', 2000000),
('A Way Out', '["Action", "Adventure"]', '["PC", "Console"]', 'help@ea.com', 4000000),
('Days Gone', '["Action", "Adventure"]', '["Console"]', 'support@bendstudio.com', 8000000),
('Hunt: Showdown', '["Shooter", "Action"]', '["PC", "Console"]', 'support@crytek.com', 3000000),
('Hell Let Loose', '["Shooter", "Action"]', '["PC"]', 'support@team17.com', 2000000),
('Squad', '["Shooter", "Action"]', '["PC"]', 'support@offworldindustries.com', 2500000),
('Beat Saber', '["Rhythm", "VR"]', '["PC", "Console"]', 'support@beat-games.com', 4000000),
('Half-Life: Alyx', '["Shooter", "VR"]', '["PC"]', 'support@valvesoftware.com', 2000000),
('Boneworks', '["Action", "VR"]', '["PC"]', 'support@stresslevelzero.com', 1000000),
('F1 23', '["Racing", "Simulation"]', '["PC", "Console"]', 'help@ea.com', 4000000),
('Assetto Corsa Competizione', '["Racing", "Simulation"]', '["PC", "Console"]', 'support@kunos-simulazioni.com', 2000000),
('iRacing', '["Racing", "Simulation"]', '["PC"]', 'support@iracing.com', 500000),
('Wreckfest', '["Racing", "Action"]', '["PC", "Console"]', 'support@bugbear.fi', 2000000),
('SnowRunner', '["Simulation", "Adventure"]', '["PC", "Console"]', 'support@saber.games', 3000000),
('Microsoft Flight Simulator X', '["Simulation"]', '["PC"]', 'flightsim-support@microsoft.com', 5000000),
('X-Plane 12', '["Simulation"]', '["PC"]', 'support@x-plane.com', 500000),
('Farming Simulator 22', '["Simulation"]', '["PC", "Console"]', 'support@giants-software.com', 6000000),
('Euro Truck Simulator 2', '["Simulation"]', '["PC"]', 'support@scssoft.com', 10000000),
('American Truck Simulator', '["Simulation"]', '["PC"]', 'support@scssoft.com', 4000000),
('Railway Empire 2', '["Simulation", "Strategy"]', '["PC"]', 'support@kalypsomedia.com', 500000),
('Two Point Campus', '["Simulation", "Strategy"]', '["PC", "Console"]', 'support@twopointstudios.com', 1000000),
('Jurassic World Evolution 2', '["Simulation", "Strategy"]', '["PC", "Console"]', 'support@frontier.co.uk', 2000000),
('Madden NFL 24', '["Sports"]', '["PC", "Console"]', 'help@ea.com', 7000000),
('NBA 2K24', '["Sports"]', '["PC", "Console"]', 'support@2k.com', 9000000),
('MLB The Show 23', '["Sports"]', '["Console"]', 'support@playstation.com', 3000000),
('PGA Tour 2K23', '["Sports"]', '["PC", "Console"]', 'support@2k.com', 1500000),
('WWE 2K23', '["Sports", "Fighting"]', '["PC", "Console"]', 'support@2k.com', 2000000),
('eFootball 2024', '["Sports"]', '["PC", "Console", "Mobile"]', 'support@konami.com', 5000000),
('Super Mega Baseball 4', '["Sports", "Arcade"]', '["PC", "Console"]', 'support@metalheadsoftware.com', 500000),
('Rocket League', '["Sports", "Action"]', '["PC", "Console"]', 'support@rocketleague.com', 75000000),
('Hokko Life', '["Simulation", "RPG"]', '["PC", "Console"]', 'support@team17.com', 500000),
('My Time at Sandrock', '["Simulation", "RPG"]', '["PC"]', 'support@pathea.net', 1000000),
('Dinkum', '["Simulation", "Adventure"]', '["PC"]', 'support@dinkum.com', 800000),
('The Sims 4', '["Simulation"]', '["PC", "Console"]', 'help@ea.com', 70000000),
('House Flipper', '["Simulation"]', '["PC", "Console"]', 'support@empyrean.games', 3000000),
('PowerWash Simulator', '["Simulation"]', '["PC"]', 'support@futurlab.co.uk', 3000000),
('PC Building Simulator', '["Simulation"]', '["PC"]', 'support@ir-ltd.net', 2000000),
('Surviving Mars', '["Simulation", "Strategy"]', '["PC"]', 'support@haemimontgames.com', 2000000),
('Prison Architect', '["Simulation", "Strategy"]', '["PC"]', 'support@double11.com', 4000000),
('Celeste', '["Platformer"]', '["PC", "Console"]', 'support@mattmakesgames.com', 5000000),
('Cuphead', '["Platformer", "Action"]', '["PC", "Console"]', 'support@studiomdhr.com', 6000000),
('Ori and the Will of the Wisps', '["Platformer", "Adventure"]', '["PC", "Console"]', 'support@moongamestudios.com', 3000000),
('Hollow Knight', '["Platformer", "Adventure"]', '["PC", "Console"]', 'support@teamcherry.com.au', 8000000),
('Spelunky 2', '["Platformer", "Roguelike"]', '["PC", "Console"]', 'support@mossmouth.com', 1500000),
('Super Meat Boy Forever', '["Platformer"]', '["PC", "Console"]', 'support@teamsupermeatboy.com', 500000),
('Guacamelee! 2', '["Platformer", "Action"]', '["PC", "Console"]', 'support@drinkboxstudios.com', 800000),
('Shovel Knight: Treasure Trove', '["Platformer", "Action"]', '["PC", "Console"]', 'support@yachtclubgames.com', 2500000),
('Blasphemous', '["Platformer", "Action"]', '["PC", "Console"]', 'support@thegamekitchen.com', 1000000),
('Dead by Daylight', '["Horror", "Multiplayer"]', '["PC", "Console", "Mobile"]', 'support@bhvr.com', 10000000),
('Outlast 2', '["Horror"]', '["PC", "Console"]', 'support@redbarrelsgames.com', 4000000),
('Amnesia: The Dark Descent', '["Horror"]', '["PC"]', 'support@frictionalgames.com', 6000000),
('SOMA', '["Horror", "Sci-Fi"]', '["PC"]', 'support@frictionalgames.com', 2000000),
('Layers of Fear 2', '["Horror"]', '["PC", "Console"]', 'support@blooberteam.com', 1000000),
('Visage', '["Horror"]', '["PC", "Console"]', 'support@sadsquarestudio.com', 800000),
('Little Nightmares', '["Puzzle", "Horror"]', '["PC", "Console"]', 'support@tarsier.se', 3000000),
('Friday the 13th: The Game', '["Horror", "Multiplayer"]', '["PC", "Console"]', 'support@fearthegun.com', 2000000),
('Ghostrunner', '["Action", "Cyberpunk"]', '["PC", "Console"]', 'support@one-more-level.com', 1500000),
('Hotline Miami 2: Wrong Number', '["Action", "Shooter"]', '["PC"]', 'support@devolverdigital.com', 1500000),
('Katana ZERO', '["Action", "Platformer"]', '["PC", "Console"]', 'support@askiisoft.com', 1000000),
('My Friend Pedro', '["Action", "Shooter"]', '["PC", "Console"]', 'support@devolverdigital.com', 1000000),
('Ruiner', '["Action", "Shooter"]', '["PC", "Console"]', 'support@reikon.com', 700000),
('Ape Out', '["Action"]', '["PC"]', 'support@devolverdigital.com', 500000),
('Enter the Gungeon', '["Roguelike", "Shooter"]', '["PC", "Console"]', 'support@dodgeroll.com', 5000000),
('Nuclear Throne', '["Roguelike", "Shooter"]', '["PC"]', 'support@vlambeer.com', 1000000),
('Risk of Rain 2', '["Roguelike", "Shooter"]', '["PC", "Console"]', 'support@hopooo.com', 4000000),
('Hades (Early Access)', '["Action", "Roguelike"]', '["PC"]', 'support@supergiantgames.com', 1000000),
('Returnal (if PC)', '["Action", "Roguelike"]', '["PC"]', 'support@housemarque.com', 500000),
('The Witness', '["Puzzle"]', '["PC", "Console", "Mobile"]', 'support@thekla.com', 2000000),
('Return of the Obra Dinn', '["Puzzle", "Adventure"]', '["PC"]', 'support@dukope.com', 1000000),
('What Remains of Edith Finch', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@giantsparrow.com', 2000000),
('Firewatch', '["Adventure"]', '["PC", "Console"]', 'support@camposanto.com', 3000000),
('Journey', '["Adventure"]', '["PC", "Console", "Mobile"]', 'support@thatgamecompany.com', 4000000),
('Gris', '["Platformer", "Adventure"]', '["PC", "Console", "Mobile"]', 'support@nomadastudio.com', 1000000),
('Inside', '["Puzzle", "Platformer"]', '["PC", "Console", "Mobile"]', 'support@playdead.com', 3000000),
('Limbo', '["Puzzle", "Platformer"]', '["PC", "Console", "Mobile"]', 'support@playdead.com', 6000000),
('Overcooked! 2', '["Co-op", "Simulation"]', '["PC", "Console"]', 'support@team17.com', 4000000),
('Moving Out', '["Co-op", "Simulation"]', '["PC", "Console"]', 'support@smtstudio.com', 1500000),
('Unravel Two', '["Platformer", "Co-op"]', '["PC", "Console"]', 'help@ea.com', 2000000),
('Don''t Starve Together', '["Survival", "Co-op"]', '["PC"]', 'support@klei.com', 8000000),
('Terraria (Mobile)', '["Adventure", "Survival"]', '["Mobile"]', 'support@re-logic.com', 10000000),
('Minecraft (Mobile)', '["Survival", "Adventure"]', '["Mobile"]', 'support@mojang.com', 300000000),
('Among Us (Mobile)', '["Strategy", "Survival"]', '["Mobile"]', 'support@innersloth.com', 400000000),
('Human: Fall Flat', '["Puzzle", "Platformer", "Co-op"]', '["PC", "Console", "Mobile"]', 'support@nomodes.com', 30000000),
('Gang Beasts', '["Fighting", "Co-op"]', '["PC", "Console"]', 'support@boneloaf.co', 3000000),
('Keep Talking and Nobody Explodes', '["Puzzle", "Co-op", "VR"]', '["PC", "Console", "Mobile"]', 'support@steelcrategames.com', 1000000),
('Death Stranding', '["Action", "Adventure"]', '["PC", "Console"]', 'support@kojimaproductions.jp', 5000000),
('Control Ultimate Edition', '["Action", "Adventure"]', '["PC", "Console"]', 'support@remedygames.com', 2000000),
('Metro Exodus Enhanced Edition', '["Shooter", "Action"]', '["PC", "Console"]', 'support@4a-games.com.mt', 1000000),
('DOOM (2016)', '["Shooter", "Action"]', '["PC", "Console"]', 'support@bethesda.net', 10000000),
('Wolfenstein II: The New Colossus', '["Shooter", "Action"]', '["PC", "Console"]', 'support@bethesda.net', 4000000),
('Titanfall 2', '["Shooter", "Action"]', '["PC", "Console"]', 'help@ea.com', 7000000),
('Apex Legends', '["Shooter", "Battle Royale"]', '["PC", "Console"]', 'help@ea.com', 100000000),
('PlayerUnknown''s Battlegrounds (PUBG)', '["Shooter", "Battle Royale"]', '["PC", "Console", "Mobile"]', 'support@pubg.com', 75000000),
('Rainbow Six Siege', '["Shooter", "Tactical"]', '["PC", "Console"]', 'support@ubisoft.com', 80000000),
('Counter-Strike: Global Offensive (CS:GO)', '["Shooter", "Tactical"]', '["PC"]', 'support@valvesoftware.com', 40000000),
('Escape from Tarkov', '["Shooter", "Survival"]', '["PC"]', 'support@battlestategames.com', 5000000),
('Insurgency: Sandstorm', '["Shooter", "Tactical"]', '["PC"]', 'support@newworldinteractive.com', 3000000),
('DOOM 64 (Remaster)', '["Shooter", "Action"]', '["PC", "Console"]', 'support@bethesda.net', 500000),
('Quake (Remastered)', '["Shooter", "Action"]', '["PC", "Console"]', 'support@bethesda.net', 750000),
('Serious Sam 4', '["Shooter", "Action"]', '["PC"]', 'support@croteam.com', 500000),
('Ion Fury', '["Shooter", "Action"]', '["PC"]', 'support@3drealms.com', 300000),
('DUSK', '["Shooter", "Action"]', '["PC"]', 'support@newblood.games', 400000),
('Amid Evil', '["Shooter", "Action"]', '["PC"]', 'support@newblood.games', 250000),
('The Outer Wilds: Echoes of the Eye', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@mobiusdigitalgames.com', 500000),
('Disco Elysium: The Final Cut', '["RPG", "Adventure"]', '["PC", "Console"]', 'support@zaum.ee', 1000000),
('Life is Strange: True Colors', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@square-enix.com', 2000000),
('Detroit: Become Human', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@quanticdream.com', 6000000),
('Beyond: Two Souls', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@quanticdream.com', 3000000),
('Heavy Rain', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@quanticdream.com', 5000000),
('The Walking Dead: The Telltale Definitive Series', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@skydance.com', 4000000),
('The Wolf Among Us', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@telltale.com', 3000000),
('Tales from the Borderlands', '["Adventure", "Narrative"]', '["PC", "Console"]', 'support@telltale.com', 2000000),
('Oxenfree', '["Adventure", "Narrative"]', '["PC", "Console", "Mobile"]', 'support@nightschoolstudio.com', 1500000),
('Night in the Woods', '["Adventure", "Narrative"]', '["PC", "Console", "Mobile"]', 'support@infinitefall.com', 1000000),
('Kentucky Route Zero', '["Adventure", "Narrative"]', '["PC"]', 'support@cardboardcomputer.com', 500000),
('Thimbleweed Park', '["Adventure", "Puzzle"]', '["PC", "Console", "Mobile"]', 'support@terribletoybox.com', 400000),
('Pikuniku', '["Adventure", "Puzzle"]', '["PC", "Console"]', 'support@devolverdigital.com', 300000),
('The Gardens Between', '["Puzzle", "Adventure"]', '["PC", "Console", "Mobile"]', 'support@thevoxelagents.com', 200000),
('Darkest Dungeon', '["RPG", "Strategy", "Roguelike"]', '["PC", "Console", "Mobile"]', 'support@redhookgames.com', 4000000),
('Slay the Spire (PC)', '["Strategy", "Card Game", "Roguelike"]', '["PC"]', 'support@megacrit.com', 4000000),
('Into the Breach', '["Strategy", "Roguelike"]', '["PC", "Console", "Mobile"]', 'support@subsetgames.com', 2000000),
('FTL: Faster Than Light', '["Strategy", "Roguelike"]', '["PC", "Mobile"]', 'support@subsetgames.com', 3000000),
('Crypt of the NecroDancer', '["Rhythm", "Roguelike"]', '["PC", "Console", "Mobile"]', 'support@braceyourselfgames.com', 1500000),
('Dicey Dungeons', '["Strategy", "Roguelike"]', '["PC"]', 'support@terrycavanagh.com', 400000),
('This War of Mine', '["Survival", "Strategy"]', '["PC", "Console", "Mobile"]', 'support@11bitstudios.com', 7000000),
('Frostpunk: Console Edition', '["Simulation", "Strategy"]', '["Console"]', 'support@11bitstudios.com', 1000000),
('Sunless Sea', '["RPG", "Adventure", "Roguelike"]', '["PC"]', 'support@failbettergames.com', 500000),
('Sunless Skies', '["RPG", "Adventure", "Roguelike"]', '["PC"]', 'support@failbettergames.com', 300000),
('Shadow Tactics: Blades of the Shogun', '["Strategy", "Tactical"]', '["PC", "Console"]', 'support@mimimigames.com', 1000000),
('Desperados III', '["Strategy", "Tactical"]', '["PC", "Console"]', 'support@mimimigames.com', 750000),
('Mutant Year Zero: Road to Eden', '["Strategy", "Tactical", "RPG"]', '["PC", "Console"]', 'support@thebeardedladiesconsulting.com', 800000),
('Gears Tactics', '["Strategy", "Tactical"]', '["PC", "Console"]', 'support@splashdamage.com', 1000000),
('Phoenix Point', '["Strategy", "Tactical"]', '["PC", "Console"]', 'support@snapshotgames.com', 500000),
('Battletech', '["Strategy", "Tactical"]', '["PC"]', 'support@hbs.net', 1000000),
('Warhammer 40,000: Mechanicus', '["Strategy", "Tactical"]', '["PC"]', 'support@kalypsomedia.com', 400000),
('Company of Heroes 2', '["Strategy", "RTS"]', '["PC"]', 'support@relic.com', 6000000),
('StarCraft II', '["Strategy", "RTS"]', '["PC"]', 'support@blizzard.com', 10000000),
('Age of Empires II: Definitive Edition', '["Strategy", "RTS"]', '["PC"]', 'support@ageofempires.com', 2000000),
('They Are Billions', '["Strategy", "RTS", "Survival"]', '["PC"]', 'support@numantiangames.com', 3000000),
('Northgard', '["Strategy", "RTS"]', '["PC"]', 'support@shirogames.com', 2000000),
('Iron Harvest', '["Strategy", "RTS"]', '["PC"]', 'support@kingart-games.com', 500000),
('Dota 2', '["Strategy", "MOBA"]', '["PC"]', 'support@valvesoftware.com', 100000000),
('League of Legends', '["Strategy", "MOBA"]', '["PC"]', 'support@riotgames.com', 150000000),
('Heroes of the Storm', '["Strategy", "MOBA"]', '["PC"]', 'support@blizzard.com', 15000000),
('World of Warcraft', '["MMORPG"]', '["PC"]', 'support@blizzard.com', 100000000),
('Final Fantasy XIV', '["MMORPG"]', '["PC", "Console"]', 'support@square-enix.com', 27000000),
('The Elder Scrolls Online', '["MMORPG"]', '["PC", "Console"]', 'help@bethsoft.com', 20000000),
('Guild Wars 2', '["MMORPG"]', '["PC"]', 'support@arena.net', 15000000),
('Black Desert Online', '["MMORPG"]', '["PC"]', 'support@pearlabyss.com', 10000000),
('Lost Ark (Western Release)', '["MMORPG", "Action"]', '["PC"]', 'support@playlostark.com', 10000000),
-- Duplicate New World (if not already listed) removed
('Mortal Shell', '["Action", "RPG"]', '["PC", "Console"]', 'support@cold-symmetry.com', 1000000),
('Nioh 2', '["Action", "RPG"]', '["PC", "Console"]', 'support@koeitecmo.com', 3000000),
('Code Vein', '["Action", "RPG"]', '["PC", "Console"]', 'support@bandainamcoent.com', 2000000),
('Remnant: From the Ashes', '["Action", "Shooter", "RPG"]', '["PC", "Console"]', 'support@gunfiregames.com', 3000000),
('Children of Morta', '["Action", "RPG", "Roguelike"]', '["PC", "Console"]', 'support@11bitstudios.com', 1000000),
('CrossCode', '["Action", "RPG"]', '["PC", "Console"]', 'support@radicalfishgames.com', 700000),
('Darksiders Genesis', '["Action", "RPG"]', '["PC", "Console"]', 'support@airshipsyndicate.com', 800000),
('Streets of Rage 4', '["Fighting", "Action"]', '["PC", "Console", "Mobile"]', 'support@dotemu.com', 2500000),
('Mortal Kombat 11', '["Fighting"]', '["PC", "Console"]', 'support@wbgames.com', 12000000),
('Dragon Ball FighterZ', '["Fighting"]', '["PC", "Console"]', 'support@bandainamcoent.com', 8000000),
('Guilty Gear -Strive-', '["Fighting"]', '["PC", "Console"]', 'support@arcsystemworks.com', 1000000),
('Injustice 2', '["Fighting"]', '["PC", "Console"]', 'support@wbgames.com', 5000000),
('Tekken 7', '["Fighting"]', '["PC", "Console"]', 'support@bandainamcoent.com', 9000000),
('Soulcalibur VI', '["Fighting"]', '["PC", "Console"]', 'support@bandainamcoent.com', 2000000),
('Brawlhalla', '["Fighting", "Platformer"]', '["PC", "Console", "Mobile"]', 'support@brawlhalla.com', 80000000),
('Slime Rancher', '["Simulation", "Adventure"]', '["PC"]', 'support@monomipark.com', 6000000),
('Spiritfarer', '["Adventure", "Simulation"]', '["PC", "Console", "Mobile"]', 'support@thunderlotusgames.com', 1000000)
;
